# Generated by Django 5.2.9 on 2026-04-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.AlterField(
            model_name='zatcadevice',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('simulation', 'Simulation'), ('production', 'Production')], default='sandbox', max_length=20, verbose_name='البيئة'),
        ),
    ]
