# Generated by Django 5.2.9 on 2026-04-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_purchaseinvoice_discount_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalyear',
            options={'permissions': [('close_fiscalyear', 'Can close fiscal year')], 'verbose_name': 'سنة مالية', 'verbose_name_plural': 'السنوات المالية'},
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12, verbose_name='الكمية'),
        ),
    ]
