# Generated by Django 5.2.9 on 2026-04-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_fiscalyear_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='الكمية'),
        ),
    ]
