# Generated by Django 5.2.9 on 2026-04-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_salesinvoiceitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='الكمية'),
        ),
    ]
