csr.common.name=TST-311571488-311571488700003
csr.serial.number=1-Alwessam|2-1.0|3-AlwessamEGS04
csr.organization.identifier=311571488700003
csr.organization.unit.name=IT
csr.organization.name=Alwessam Contracting Company
csr.country.name=SA
csr.invoice.type=1100
csr.location.address=Jeddah
csr.industry.business.category=Construction
