csr.common.name=TST-886431145-311571488700003 
csr.serial.number=1-Alwessam|2-1.0|3-77a5d979 
csr.organization.identifier=311571488700003 
csr.organization.unit.name=IT 
csr.organization.name=Alwessam Company 
csr.country.name=SA 
csr.invoice.type=0100 
csr.location.address=Riyadh 
csr.industry.business.category=Construction 
